version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_seguridad
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: university_seguridad
    ports:
      - '5432:5432'
